### ISSUE TITLE
Add table terraform_module

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-terraform#14]
**Is your feature request related to a problem? Please describe.**
When using modules in my TF config files, the plugin does not parse them correctly

**Describe the solution you'd like**
Terraform plugin should know how to parse module blocks

**Describe alternatives you've considered**
None

**Additional context**
Module examples - https://www.terraform.io/language/modules/develop/composition

**Comment by dmthomson** [comment]
This would be a great feature for the terraform plugin

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-terraform/pull/28
