### ISSUE TITLE
Add `source` and `end_line` column to relevant tables

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe-plugin-terraform#23]
All tables contain a `start_line` but there's no `end_line`. Also, the `source` of the block should also be included

**Comment by cbruno10** [comment]
Hey @binaek , the reason there's no `source` or `end_line` columns is that the parser (Kics) we're using to parse Terraform files doesn't include these in their output. So these are columns we'd like to have, but we'd either need to parse the files in this package, or contribute back to or fork the Kics parser package.

All of these options are possible, but would require significant effort and they're not something we currently have prioritized. We're open to looking at community contributions or we may take these column additions up ourselves in the future.
