### ISSUE TITLE
Allow authentication via GitHub PAT when when working with private repositories

### ISSUE THREAD

**Issue by TrongBYM** [turbot/steampipe-plugin-terraform#32]
**Is your feature request related to a problem? Please describe.**
The `paths` configuration can include GitHub repository URLs as described in the [documentation](https://hub.steampipe.io/plugins/turbot/terraform). However, the URLs will not be accessible if the repositories are private due to the call to GitHub being unauthenticated.  

**Describe the solution you'd like**
Implement the optional use of GitHub PAT tokens akin to how it is performed in the [Steampipe GitHub plugin](https://hub.steampipe.io/plugins/turbot/github#configuration). Either an explicit `github_token` config declaration or read from ENV VARs is sufficient for this use-case.

**Describe alternatives you've considered**
Not sure if it is a good solution, but consider using the authenticated session provided by [GitHub cli](https://cli.github.com/) aka. `gh` to authenticate when using the plugin. Or integrate with [Steampipe GitHub plugin](https://hub.steampipe.io/plugins/turbot/github#configuration), but this I bet is less appealing.

**Additional context**
I want to access **organizational** private repositories, and I am not sure if such repositories differ from normal private repositories.

**Comment by cbruno10** [comment]
Hey @TrongBYM , our SDK uses the [hashicorp/go-getter](https://github.com/hashicorp/go-getter) package to retrieve files from Git, S3, and other remote sources. According to their README, they support passing in a query parameter called [sshkey](https://github.com/hashicorp/go-getter#git-git).

We don't have an example for this yet (we should), but including a URL in `paths` like `ssh://git@github.com/exampleorg/test-private-repo?sshkey=<base64-encoded SSH key here>` should allow this plugin to access the files.

**Comment by cbruno10** [comment]
@gabrielsoltz If you're referring to the URL style, passing in SSH style URLs should also work according to the [go-getter README](https://github.com/hashicorp/go-getter#git-git), but if you're seeing any different results, please let us know what your `paths` arg is set to and what the unexpected results are and then we can troubleshoot more.

**Comment by bigdatasourav** [comment]
Hey @pdecat, my apologies for the lack of communication regarding this issue.

Could you please try the below format and let us know if it is working for you - 

```
connection "terraform" {
  plugin = "terraform"
  paths = [
    "git::ssh://git@github.com/test_org/test_repo//*.tf"
  ]
}
```

**Comment by cbruno10** [comment]
@bigdatasourav Do we need to update our docs as well to fix or include that example?
