### ISSUE TITLE
Add support to parse Terraform state files

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-terraform#45]
**Is your feature request related to a problem? Please describe.**
I'd like to query resources with states as close to the deployed resources

**Describe the solution you'd like**
Parsing state files to get resource information would be helpful

**Describe alternatives you've considered**
Look at plan files or base TF config files

**Additional context**
N/A

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-terraform/pull/47
