### ISSUE TITLE
Crash when using default connection config and running in a directory without `tfplan.json`

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-terraform#55]
**Describe the bug**
I installed the Terraform plugin, went to a blank directory, and then ran `select * from terraform_resource` and received the error `Error: failed to get directory specified by the source tfplan.json: relative paths require a module with a pwd (SQLSTATE HV000)`

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
v0.8.0

**To reproduce**
See above

**Expected behavior**
No rows should be returned

**Additional context**

**Comment by bigdatasourav** [comment]
@cbruno10, If we are running in a directory that does not contain tfplan.json, the [GetSourceFiles](https://github.com/turbot/steampipe-plugin-terraform/blob/main/terraform/utils.go#L103) function returns the above error, which comes from SDK. Should we handle the error and return an empty row?

**Comment by cbruno10** [comment]
@bigdatasourav Do we have this issue in general across other plugins, i.e., if a user provides an exact filename in any file path config arg, we receive an error instead of an empty row? I think returning empty rows instead of erroring if the file(s) do not exist is better behaviour.

**Comment by cbruno10** [comment]
@bigdatasourav Do other plugins currently crash when providing an exact filename that doesn't exist?

**Comment by bigdatasourav** [comment]
Yes, @cbruno10, the other plugins wherever we have used the GetSourceFiles function crash if the filename does not exist, as we never handled the error.
