### ISSUE TITLE
*.tf.json terraform configure json  format not supported. 

### ISSUE THREAD

**Issue by jan4984** [turbot/steampipe-plugin-terraform#62]

**Comment by bigdatasourav** [comment]
Hey @jan4984, Sorry for the delayed response. Could you please provide us with the following - 

1. Sample of your SPC file.
2. The query which you are trying to execute with the error message if you are getting any.

**Comment by bigdatasourav** [comment]
Hey @jan4984, we're closing this issue as we have yet to hear back from you; please feel free to reopen if you want to share anything.
